include(":core-impl")
include(":movies-api")
include(":movies-impl")
include(":login-api")
include(":login-impl")
include(":app")
project(":login-api").projectDir = File(rootDir, "login/login-api/")
project(":login-impl").projectDir = File(rootDir, "login/login-impl/")
project(":movies-api").projectDir = File(rootDir, "movies/movies-api/")
project(":movies-impl").projectDir = File(rootDir, "movies/movies-impl/")
project(":core-impl").projectDir = File(rootDir, "core/core-impl/")
rootProject.name = "Architecture Example"